model:
  target: src.models.SingleModel
  params:
    encoder_params:
      type: transformer
      n_heads: 8
      v_heads: 8
      n_layers: 16
    emb_dim: 128
    d_model: 128
    extra_features:
      - ck_encodings
      - ss_encodings
      - sasa_encodings
      - bfactor_encodings
    task_type: classification

optimizer:
  target: torch.optim.SGD
  params:
    lr: 0.001
    weight_decay: 5e-4
    momentum: 0.9 
  loss_fn: torch.nn.BCELoss

scheduler:
  target: torch.optim.lr_scheduler.LambdaLR
  lr_milestones: 
    - 300
    - 400
  lr_gamma: 0.1

data:
  batch_size: 8
  workers: 8
  train_data:
    target: src.datasets.EnzymeClass
    params:
      split_type: random
      split: train
      resolution: atom
  valid_data:
    target: src.datasets.EnzymeClass
    params:
      split_type: random
      split: val
      resolution: atom
  test_data:
    - target: src.datasets.EnzymeClass
      params:
        split_type: random
        split: test
        resolution: atom
