model:
  target: src.models.ProbeModel
  params:
    d_model: &d_model 128
    layers: 5
    input_encs:
      - stability
    input_dims:
      - 20
    pooling: mean
    task_type:
      - protein_pair
      - regression

data:
  batch_size: 128
  workers: 8
  train_data:
    target: src.datasets.StructureSimilarity
    params:
      split_type: &split_type random
      split: train
      resolution: residue
  valid_data:
    target: src.datasets.StructureSimilarity
    params:
      split_type: *split_type
      split: val
      resolution: residue
  test_data:
    - target: src.datasets.StructureSimilarity
      params:
        split_type: *split_type
        split: test
        resolution: residue

training:
  epochs: 10
  lr: 1e-3
  weight_decay: 5e-4
