model:
  target: src.models.SingleModel
  params:
    embed_dim: &embed_dim 32
    d_model: &d_model 256
    feas:
      - seq
      - ck
      - ss
      # - asa
      - bfactor
      # - lp
      # - hydro
      # - stability
      # - entropy
      # - orc
    input_dims:
      - 16
      - 8
      # - 16
      - 22
      # - 12
      # - 22
      # - 20
      # - 12
      # - 16
    encoder:
      type: cdconv
      geometric_radii:
        - 8.0
        - 12.0
        - 16.0
        - 20.0
      sequential_kernel_size: 15
      kernel_channels: 32
      channels:
        - 256
        - 512
        - 1024
        - 2048
      base_width: 16.0
      embed_dim: *embed_dim
      d_model: *d_model
    feature_fusion: gate
    pooling: mean
    task_type: 
      - protein
      - multilabel

data:
  batch_size: 24
  workers: 4
  train_data:
    target: src.datasets.GeneOntology
    params:
      branch: &branch mf
      split_type: &split_type structure
      split: train
      resolution: residue
  valid_data:
    target: src.datasets.GeneOntology
    params:
      branch: *branch
      split_type: *split_type
      split: val
      resolution: residue
  test_data:
    - target: src.datasets.GeneOntology
      params:
        branch: *branch
        split_type: *split_type
        split: test
        resolution: residue

training:
  epochs: 100
  lr: 1e-4
  weight_decay: 1e-06
      