model:
  target: src.models.SingleModel
  params:
    embed_dim: &embed_dim 32
    d_model: &d_model 128
    feas:
      - seq
      # - ck
      # - ss
      - asa
      # - bfactor
      - lp
      # - hydro
      # - stability
      - entropy
      # - orc
    input_dims:
      # - 16
      # - 8
      - 16
      # - 22
      - 12
      # - 22
      # - 20
      - 12
      # - 16
    encoder:
      type: gnn
      n_layers: 5
      embed_dim: *embed_dim
      d_model: *d_model
      gnn_type: gin
      dropout: 0.2
      use_edge_attr: False
      pe: null
    feature_fusion: gate
    task_type: 
      - residue_pair
      - binary

data:
  batch_size: 2
  workers: 4
  train_data:
    target: src.datasets.ProteinProteinInterface
    params:
      split_type: &split_type structure
      split: train
      resolution: residue
  valid_data:
    target: src.datasets.ProteinProteinInterface
    params:
      split_type: *split_type
      split: val
      resolution: residue
  test_data:
    - target: src.datasets.ProteinProteinInterface
      params:
        split_type: *split_type
        split: test
        resolution: residue

training:
  epochs: 50
  lr: 1e-3
  weight_decay: 1e-06
  metrics:
    - auroc
  scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
      T_max: 100
      eta_min: 1e-6
