model:
  target: src.models.ProbeModel
  params:
    d_model: &d_model 128
    layers: 5
    input_encs:
      - orc
    input_dims:
      - 16
    pooling: mean
    task_type: 
      - protein
      - classification

data:
  batch_size: 24
  workers: 4
  train_data:
    target: src.datasets.EnzymeClass
    params:
      split_type: &split_type structure
      split: train
      resolution: residue
  valid_data:
    target: src.datasets.EnzymeClass
    params:
      split_type: *split_type
      split: val
      resolution: residue
  test_data:
    - target: src.datasets.EnzymeClass
      params:
        split_type: *split_type
        split: test
        resolution: residue

training:
  epochs: 50
  lr: 1e-3
  weight_decay: 5e-4
