model:
  target: src.models.ProbeModel
  params:
    d_model: &d_model 128
    layers: 5
    input_encs:
      - asa
    input_dims:
      - 16
    pooling: mean
    task_type: 
      - protein
      - multilabel

data:
  batch_size: 24
  workers: 8
  train_data:
    target: src.datasets.GeneOntology
    params:
      branch: &branch bp
      split_type: &split_type structure
      split: train
      resolution: residue
  valid_data:
    target: src.datasets.GeneOntology
    params:
      branch: *branch
      split_type: *split_type
      split: val
      resolution: residue
  test_data:
    - target: src.datasets.GeneOntology
      params:
        branch: *branch
        split_type: *split_type
        split: test
        resolution: residue

training:
  epochs: 50
  lr: 1e-3
  weight_decay: 5e-4
      